### PR TITLE
ECMS-7883 : Make the delete button not displayed for default folders

### PR DESCRIPTION
**Pull request by mdiha**
In order to make sure that the delete button is not displayed for default folders under "/Users" folder, i added an if statement at the accept method in CanDeleteNodeFilter class, the if statement checks if the current folder is a system folder by its "exo:owner" node property and if it is under "/Users"  folder and returns false if so.

### CODE REVIEW

**Comment by mdiha** [comment]
I moved the check statement to the CanDeleteNodeFilter class at the accept method.

**Comment by mdiha** [comment]
Yes actually it is a regression from 5.1 i will check it and try to find what caused the issue.

**Comment by thomasdelhomenie** [comment]
@mdiha @trongtt I updated the PR. This issue is related to the session used (system instead of user). I did some tests, it did not see any regression. Can you check on your side please ?

**Comment by mdiha** [comment]
@thomasdelhomenie i have tested and there is a strange behavior when accessing the shared documents folder, the shared files aren't displayed correctly

**Comment by mdiha** [comment]
The strange behavior when accessing the shared documents folder should be fixed by the PR ECMS-7888

**Pull request merged**
