### PR TITLE
ECMS-7820 : update calculation of versions display names

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
This fix updates the calculation of the display names of the versions to make sure the versions index (name) and display name are correct.

### CODE REVIEW

**Comment by boubaker** [comment]
I didn't tested it, does this mean that the draft version will start with 1 instead of 0 ?

**Comment by boubaker** [comment]
This functional change should be referenced as improvement in Document Versioning Spec if approved by PM (cc @hghorbel )

**Comment by thomasdelhomenie** [comment]
No functional change is intended for this fix, first version must still be 0. I don't reproduce the issue, the first version is 0 (as in the unit tests) :
selection_031
Can you describe the test you did exactly please ?

**Comment by boubaker** [comment]
I 've built the project and deployed the new JAR :-)

**Comment by boubaker** [comment]
Ah yes, I 've missed the second jar, but even with the second one, I have got this:
after-patch

**Comment by boubaker** [comment]
The exact use case:
Upload new file, checkin/checkout and list versions

**Comment by thomasdelhomenie** [comment]
Ah, the current issue is with the new way to manage version (button "Upload new version" or drag and drop on the file), not with the button checkin/checkout. Can you try again with this button please ?

**Comment by thomasdelhomenie** [comment]
I also tried with Checkin/Checkout buttons and got the same results ("Original Version" is displayed for version 0). What I did:
* go to Personal Documents, then in the Documents folder
* upload a xml file
* open the xml file
* click on Checkin, then on Checkout (do it twice)
--> I see the same thing than in this comment : https://github.com/exodev/ecms/pull/415#issuecomment-403431038

**Comment by boubaker** [comment]
Ok, I 'll try to download a fresh eXo Bundle and try again, my be I missed another thing

**Comment by boubaker** [comment]
It seems working with a fresh installation. Well done (y)

**Comment by thomasdelhomenie** [comment]
Thanks! :+1:

**Pull request merged**
