### PR TITLE
SOC-5472 : retrieve the space root navigation URI from the API instead of guessing it from the space group id since it can change when the space is renamed

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
This new version of the fix does not rely on RequestContext to work in any context (activity stream, notification email, ...).

### CODE REVIEW

**Comment by boubaker** [comment]
The question is, why should we add the navigations of the space under a parent navigation ?
IMO, if possible, we should use all the navigations of the space that are just under root navigation and don't create a parent navigation?

**Comment by thomasdelhomenie** [comment]
I am not sure to understand. Can you point the code causing trouble in the PR please ?

**Comment by boubaker** [comment]
My feedback can be treated in another issue.
In fact the URL of applications in spaces are:
/portal/g/SPACE_GROU_URI/PRETTY_NAME/APP_URI
example: /portal/g/:spaces:staging_extension_1/staging_extension_1/wiki
IMO, this should be:
/portal/g/SPACE_GROU_URI/APP_URI
example: /portal/g/:spaces:staging_extension_1/wiki
without an additional navigation node with dynamic name equal to PRETTY_NAME

Using a parent node with URI=PRETTY_NAME means that we cannot generate the space Navigations from GateIn Site Group Template because the URI of the navigation can't be dynamic.

Another feedback, related to PR. IMO, we should use [GateIN Portal API](https://docs.jboss.org/author/display/GTNPORTAL36/Portal+API) if possible.

**Comment by thomasdelhomenie** [comment]
@boubaker PR updated to use Portal Navigation API.

**Pull request closed without merging**
