### PR TITLE
ECMS-7454:should not use ThreadLocal for user navigation, use convers…

### PR DESCRIPTION
**Pull request by azaoui**
ECMS-7454:should not use ThreadLocal for user navigation

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
The PR looks good. Do you see any drawback of this solution ?
Did you check that the request to retrieve the navigation is only done once per session ?

**Comment by azaoui** [comment]
PR updated with 1)

**Comment by azaoui** [comment]
for the 2) if approved it will remove the var from home page if the breadcump template note use 
If ok will remove it

**Comment by azaoui** [comment]
Not a space, actually it's a kind of special character "not visible" added after reverting the file 
 the diff is showing old last line  as modified, when conceptually its not , try to compare the file outside the pull request. anyway will try to remove it

**Comment by azaoui** [comment]
removed

**Comment by boubaker** [comment]
Have you tested this to see if there is no objects are added anymore in the memory ?
It's important and crucial to ensure that it doesn't happen with this change.

**Comment by azaoui** [comment]
Before fix with 200 concurrent access to home page that contains more then one SCV portlet 106 entries found  not released from memory of type Thread => ThreadLocalMap => ThreadLocalMap$Entry with the String key format    portalName + " " + username + " " + navigationScope;
beforelocalthred
key

After applying the patch no entries found  and removeNavigationAsJson executed with success for all users after the page rendering.

Congratulation!

**Pull request closed without merging**
