### PR TITLE
ECMS-7889 : add write permissions on ecms data for Web Contributors

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
Thanks to PLF-8035, the read permissions for all users (any) has been removed from dms-system nodes.
But Web Contributors should be able to see (and administrate) these data through the Content Administration application.

This fix adds the read/write permissions on these nodes for Web Contributors and updates the upgrade plugins accordingly.

@trongtt I noticed another permission issue : the template nodes (for example /exo:ecm/templates/nt:file) still have read/write permissions for administrators and read permissions for any. This leads to web contributors not been able to update templates in Content Administration application. I did not fix it yet as part of this fix because I noticed we have the same issue in 5.1 (web contributors cannot update templates) and I wanted your opinion. WDYT ?

### CODE REVIEW

**Comment by trongtt** [comment]
@thomasdelhomenie is it acceptable to update an existing upgrade plugin ? because of still being the same major version ?

About Content Administration application, I was confusing about the two layers of permission management, one from JCR privilege (storage itself) and the other from the app (Drives permissions in this case). Here webdav totally relies on JCR privilege. So I think we should make it clear in use for application level permission itself. Let's say that we should use system JCR session for any operations in Content Administration app, as long as users have right to use the app.

**Comment by thomasdelhomenie** [comment]
> is it acceptable to update an existing upgrade plugin ? because of still being the same major version ?

It will be transparent for customers since this upgrade plugin has been added for 5.2 only (which is not released yet), so they did not run the upgrade plugin yet. The only issue will be for Tribe which has already run the upgrade plugin (in a milestone version). We will have to hack it to execute again the upgrade plugin.

> About Content Administration application, I was confusing about the two layers of permission management, one from JCR privilege (storage itself) and the other from the app (Drives permissions in this case). Here webdav totally relies on JCR privilege. So I think we should make it clear in use for application level permission itself. Let's say that we should use system JCR session for any operations in Content Administration app, as long as users have right to use the app.

That makes sense. So you mean we should always use the system session in the Content Administration application, right ?

> BTW, I see the template nodes (for example /exo:ecm/templates/nt:file) still have read/write permission for administrators only, could you double check ?

Right, my bad.

**Comment by trongtt** [comment]
> That makes sense. So you mean we should always use the system session in the Content Administration application, right ?

Yes if we define that who can access to the app is also able to perform any operations in the app.

**Comment by thomasdelhomenie** [comment]
@trongtt I updated the PR according to your feedback.

**Pull request merged**
